local Category = "Personal"

-- Porsche 911 (901) --
local V = {
	Name = "911 Carrera Electric (901)",
	Model = "models/DiggerCars/PORSCHE_901RS/ev1.mdl",
	Class = "gmod_sent_vehicle_fphysics_base",
	Category = Category,
	Members = {
		ModelInfo = {
			Color = Color(20, 40, 25),
		},
		Mass = 1090,
		MaxHealth = 3000,
		FuelType = FUELTYPE_ELECTRIC,
		FuelFillPos = Vector(35, 25, 20),
		CustomWheels = true,
		CustomSuspensionTravel = 15,
		LightsTable = "911e",
		CustomWheelModel = "models/DiggerCars/PORSCHE_901/wheel.mdl",
		CustomWheelPosFL = Vector(48.3, 29.2, 11),
		CustomWheelPosFR = Vector(48.3, -29.2, 11),
		CustomWheelPosRL = Vector(-43, 28.8, 10),
		CustomWheelPosRR = Vector(-43, -28.8, 10),
		CustomWheelAngleOffset = Angle(0, 90, 0),
		CustomWheelCamber = -0.5,
		FrontWheelMass = 40,
		RearWheelMass = 40,
		CustomMassCenter = Vector(-5, 0, -1),
		CustomSteerAngle = 35,
		SeatOffset = Vector(-8, -12.4, 30),
		SeatPitch = 0,
		SeatYaw = 90,
		PassengerSeats = {
			{
				pos = Vector(5, -13, -2),
				ang = Angle(0, -90, 20)
			}
		},
		Attachments = {
			{
				model = "models/DiggerCars/PORSCHE_901RS/BaseV1.mdl",
				color = Color(255, 255, 255, 255),
				useVehicleColor = true,
				pos = Vector(0, 0, 0),
				ang = Angle(0, 0, 0),
				nosolid = true
			},
			{
				model = "models/DiggerCars/PORSCHE_901RS/INT.mdl",
				color = Color(255, 255, 255, 255),
				useVehicleColor = true,
				pos = Vector(0, 0, 0),
				ang = Angle(0, 0, 0),
				nosolid = true
			},
			{
				model = "models/cyckl/plates/license_gb_old.mdl",
				color = Color(255, 255, 255, 255),
				useVehicleColor = false,
				pos = Vector(-80, 0, 9),
				ang = Angle(-20, 180, 0),
				nosolid = true
			}
		},
		FrontHeight = 8,
		FrontConstant = 90000,
		FrontDamping = 2000,
		FrontRelativeDamping = 2500,
		RearHeight = 8,
		RearConstant = 90000,
		RearDamping = 2000,
		RearRelativeDamping = 2500,
		FastSteeringAngle = 10,
		SteeringFadeFastSpeed = 535,
		TurnSpeed = 5,
		MaxGrip = 40,
		Efficiency = 1.25,
		GripOffset = -2,
		BrakePower = 40,
		IdleRPM = 0,
		LimitRPM = 20000,
		PeakTorque = 150,
		PowerbandStart = 0,
		PowerbandEnd = 20000,
		Turbocharged = true,
		Supercharged = true,
		DoNotStall = true,
		PowerBias = 0,
		EngineSoundPreset = 0,
		Sound_Idle = "",
		Sound_IdlePitch = 0.5,
		Sound_Mid = "",
		Sound_MidPitch = 1.0,
		Sound_MidVolume = 2,
		Sound_MidFadeOutRPMpercent = 100,
		Sound_MidFadeOutRate = 1,
		Sound_High = "",
		Sound_HighPitch = 0,
		Sound_HighVolume = 0,
		Sound_HighFadeInRPMpercent = 0,
		Sound_HighFadeInRate = 0,
		Sound_Throttle = "",
		Sound_ThrottlePitch = 0,
		Sound_ThrottleVolume = 0,
		DifferentialGear = 1.4,
		Gears = {-0.1, 0, 0.1}
	}
}
list.Set("simfphys_vehicles", "sim_fphys_91164_electric_cyckl", V)

-- Porsche 911 Carrera RS 2.7 (901) --
local V = {
	Name = "911 Carrera RS Electric (901)",
	Model = "models/DiggerCars/PORSCHE_901RS/rsv3.mdl",
	Class = "gmod_sent_vehicle_fphysics_base",
	Category = Category,
	Members = {
		ModelInfo = {
			Color = Color(0, 0, 0),
		},
		Mass = 1070,
		MaxHealth = 3000,
		FuelType = FUELTYPE_ELECTRIC,
		FuelFillPos = Vector(35, 25, 20),
		CustomWheels = true,
		CustomSuspensionTravel = 15,
		LightsTable = "911e",
		CustomWheelModel_R = "models/DiggerCars/PORSCHE_901/wheel.mdl",
		CustomWheelModel = "models/DiggerCars/PORSCHE_901/wheel.mdl",
		CustomWheelPosFL = Vector(48.3, 29.2, 11),
		CustomWheelPosFR = Vector(48.3, -29.2, 11),
		CustomWheelPosRL = Vector(-43, 28.8, 10),
		CustomWheelPosRR = Vector(-43, -28.8, 10),
		CustomWheelAngleOffset = Angle(0, 90, 0),
		CustomWheelCamber = -0.5,
		FrontWheelMass = 40,
		RearWheelMass = 40,
		CustomMassCenter = Vector(-5, 0, -1),
		CustomSteerAngle = 35,
		SeatOffset = Vector(-8, -12.4, 30),
		SeatPitch = 0,
		SeatYaw = 90,
		PassengerSeats = {
			{
				pos = Vector(5, -13, -2),
				ang = Angle(0, -90, 20)
			}
		},
		Attachments = {
			{
				model = "models/DiggerCars/PORSCHE_901RS/BaseV1.mdl",
				color = Color(255, 255, 255, 255),
				useVehicleColor = true,
				pos = Vector(0, 0, 0),
				ang = Angle(0, 0, 0),
				nosolid = true
			},
			{
				model = "models/DiggerCars/PORSCHE_901RS/INT.mdl",
				color = Color(255, 255, 255, 255),
				useVehicleColor = true,
				pos = Vector(0, 0, 0),
				ang = Angle(0, 0, 0),
				nosolid = true
			},
			{
				model = "models/cyckl/plates/license_gb_old.mdl",
				color = Color(255, 255, 255, 255),
				useVehicleColor = false,
				pos = Vector(84, 0, 2.3),
				ang = Angle(0, 0, 0),
				nosolid = true
			},
			{
				model = "models/cyckl/plates/license_gb_old.mdl",
				color = Color(255, 255, 255, 255),
				useVehicleColor = false,
				pos = Vector(-80, 0, 9),
				ang = Angle(-20, 180, 0),
				nosolid = true
			}
		},
		FrontHeight = 8,
		FrontConstant = 90000,
		FrontDamping = 2000,
		FrontRelativeDamping = 2500,
		RearHeight = 8,
		RearConstant = 90000,
		RearDamping = 2000,
		RearRelativeDamping = 2500,
		FastSteeringAngle = 10,
		SteeringFadeFastSpeed = 535,
		TurnSpeed = 5,
		MaxGrip = 40,
		Efficiency = 1.25,
		GripOffset = -2,
		BrakePower = 40,
		IdleRPM = 0,
		LimitRPM = 20000,
		PeakTorque = 220,
		PowerbandStart = 0,
		PowerbandEnd = 20000,
		Turbocharged = true,
		Supercharged = true,
		DoNotStall = true,
		PowerBias = 0,
		EngineSoundPreset = 0,
		Sound_Idle = "",
		Sound_IdlePitch = 0.5,
		Sound_Mid = "",
		Sound_MidPitch = 1.0,
		Sound_MidVolume = 2,
		Sound_MidFadeOutRPMpercent = 100,
		Sound_MidFadeOutRate = 1,
		Sound_High = "",
		Sound_HighPitch = 0,
		Sound_HighVolume = 0,
		Sound_HighFadeInRPMpercent = 0,
		Sound_HighFadeInRate = 0,
		Sound_Throttle = "",
		Sound_ThrottlePitch = 0,
		Sound_ThrottleVolume = 0,
		DifferentialGear = 1.4,
		Gears = {-0.1, 0, 0.1}
	}
}
list.Set("simfphys_vehicles", "sim_fphys_911carrerars27_electric_cyckl", V)

-- Porsche 911 Turbo S (991.2) --
local V = {
	Name = "911 Turbo S Electric (991.2)",
	Model = "models/DiggerCars/PORSCHE_991Turbo/v7.mdl",
	Class = "gmod_sent_vehicle_fphysics_base",
	Category = Category,
	Members = {
		ModelInfo = {
			Color = Color(20, 20, 20),
			WheelColor = Color(180, 180, 180),
		},
		Mass = 1700,
		MaxHealth = 3000,
		FuelType = FUELTYPE_ELECTRIC,
		FuelFillPos = Vector(38, -28, 29),
		LightsTable = "991turbo",
		CustomWheels = true,
		CustomSuspensionTravel = 15,
		CustomWheelModel = "models/DiggerCars/PORSCHE_991gt3rs/fw.mdl",
		CustomWheelPosFL = Vector(49.3, 29, 18),
		CustomWheelPosFR = Vector(49.3, -29, 18),
		CustomWheelPosRL = Vector(-48.5, 32, 18),
		CustomWheelPosRR = Vector(-48.5, -32, 18),
		CustomWheelAngleOffset = Angle(0, -90, 0),
		CustomMassCenter = Vector(-1, 0, -8),
		CustomSteerAngle = 35,
		SeatOffset = Vector(-11, -13.5, 36),
		SeatPitch = 0,
		SeatYaw = 90,
		PassengerSeats = {
			{
				pos = Vector(-3, -13, 4),
				ang = Angle(0, -90, 20)
			}
		},
		Attachments = {
			{
				model = "models/cyckl/plates/license_gb.mdl",
				color = Color(255, 255, 255, 255),
				useVehicleColor = false,
				pos = Vector(-89, 0, 20),
				ang = Angle(-20, 180, 0),
				nosolid = true
			}
		},
		FrontHeight = 8,
		FrontConstant = 130000,
		FrontDamping = 2000,
		FrontRelativeDamping = 3500,
		RearHeight = 8,
		RearConstant = 130000,
		RearDamping = 2000,
		RearRelativeDamping = 3500,
		FastSteeringAngle = 10,
		SteeringFadeFastSpeed = 535,
		TurnSpeed = 8,
		MaxGrip = 60,
		Efficiency = 1.25,
		GripOffset = -3,
		BrakePower = 40,
		IdleRPM = 0,
		LimitRPM = 20000,
		PeakTorque = 300,
		PowerbandStart = 0,
		PowerbandEnd = 20000,
		Turbocharged = true,
		Supercharged = true,
		DoNotStall = true,
		PowerBias = 0,
		EngineSoundPreset = 0,
		Sound_Idle = "",
		Sound_IdlePitch = 0,
		Sound_Mid = "",
		Sound_MidPitch = 0.55,
		Sound_MidVolume = 1,
		Sound_MidFadeOutRPMpercent = 100,
		Sound_MidFadeOutRate = 1,
		Sound_High = "",
		Sound_HighPitch = 0,
		Sound_HighVolume = 0,
		Sound_HighFadeInRPMpercent = 0,
		Sound_HighFadeInRate = 0,
		Sound_Throttle = "",
		Sound_ThrottlePitch = 0,
		Sound_ThrottleVolume = 0,
		DifferentialGear = 1.1,
		Gears = {-0.1, 0, 0.1}
	}
}
list.Set("simfphys_vehicles", "sim_fphys_991turbo_electric_cyckl", V)